### ISSUE TITLE
Feature Request: api namespace

### ISSUE THREAD

**Issue by bantic** [trek/pretender#29]
Would you be open to a PR adding options to the `Pretender` constructor that allowed passing in a `namespace`, similar to Ember Data's namespace property?

Example usage:
```
server = new Pretender(function(){
   this.get('users/:user_id', function() { ... });
}, {namespace: 'api/v1'});
```

This will intercept a GET request to `/api/v1/users/:user_id`.

**Comment by trek** [comment]
The constructor now takes many maps, so I don't see this going in. A better syntax with this change would be a namespace function:

```javascript
server = new Pretender(function(){
   this.namespace('/api/v1', function(){
    this.get('users/:user_id', function() { ... });
   });
});
```
