### ISSUE TITLE
Pretender doesn't recognize routes with query params

### ISSUE THREAD

**Issue by bcardarella** [trek/pretender#31]
Failing test:

```js
test("can register queryParam urls", function(){
  var queryCalled  = false;
  var noQueryCalled = false;
  pretender.get('/some/path?a=1&b=2', function(request){
    queryCalled = true;
  });
  pretender.get('/some/path', function(request){
    noQueryCalled = true;
  });
 
  $.ajax({url: '/some/path?a=1&b=2'});
  ok(!noQueryCalled, 'should be false');
  ok(queryCalled, 'should be true');
});
```

I have tracked the problem down to RouteRecognizer: https://github.com/tildeio/route-recognizer/blob/master/lib/route-recognizer.js#L475-L523

It appears that RotueRecognizer will register the original path along with the queryParams. However in the linked function above the queryParams are striped from the path and no handler is found for the truncated path.

My use-case is https://github.com/dockyard/ember-cli-proxy-fixtures. This module is recording request responses during the test suite for faster playback via Pretender on future runs.

**Comment by trek** [comment]
Can you open this on the route recognize repo? This isn't a feature we can support without a change there.

**Comment by bdvholmes** [comment]
For reference [the issue on route-recognizer](https://github.com/tildeio/route-recognizer/issues/53).
