### ISSUE TITLE
Server Inheritance / Easier map sharing

### ISSUE THREAD

**Issue by trek** [trek/pretender#42]
Ideally, we'd like to have new Pretender instances be created from existing instances. This would allow you to re-use a set of routes in tests. I think this would be especially useful for nested tests. You can get this behavior today by sharing route maps, but it's a little manual and limited to a depth of 1.

This will likely require pretty major internal refactoring?

**Comment by esbanarango** [comment]
:+1:

**Comment by esbanarango** [comment]
> You can get this behavior today by sharing route maps

@trek How do you actually do that?

**Comment by trek** [comment]
```
var fn = function() {}

var a = new Prentender(fn);
var b = new Pretender(fn);
```

**Comment by trek** [comment]
https://github.com/trek/pretender/releases/tag/0.6.0

**Comment by esbanarango** [comment]
![giphy](https://cloud.githubusercontent.com/assets/1156865/5790804/d6811d2a-9e77-11e4-8bb6-68baebe5c169.gif)
