### ISSUE TITLE
Question about using/implementing a front controller

### ISSUE THREAD

**Issue by samselikoff** [trek/pretender#53]
I'm wondering if it's possible to dynamically register request handlers at time of request, i.e. look up a handler when the actual request is made. I'd like to do this so that my addon can respond to requests by looking up a handler if it exists at, say, `/app/pretender/routes/some-route.js`.

Is this possible now? I was thinking about doing it in the `unhandledRequest`, but I'm not sure I can invoke `handleRequest` from there? Any suggestions about how to approach this/work a possible PR?

**Comment by trek** [comment]
This seems possible by implementing `unhandledRequest`, the way you're descrbing but you'd need to undo the bookkeeping around unhandled requests. I don't think this use case is general enough to make it into the main library though.

**Comment by samselikoff** [comment]
Even with something low touch, like adding a `requestReceived` hook?

**Comment by trek** [comment]
Probbly I need to see some code to decide

**Comment by samselikoff** [comment]
I worked around this so figured I'd close for now. thx :)
