### ISSUE TITLE
How can I use posted data?

### ISSUE THREAD

**Issue by kgish** [trek/pretender#64]
How can I access the data passed via a post request?

Based on the [evil trout video on pretender](https://www.youtube.com/watch?v=b5VUnc_GsV4) I'd like to do something like this:
```
this.post('/api/v1/token', function(request){
    console.log(request);
    var data = parsePostData(request.requestBody); // doesn't work
   // check username and password and if okay
    var response = {
        "access_token": "myaccesstoken==",
        "token_type": "bearer"
    };
    return [200, {}, response];
```

**Comment by trek** [comment]
I'm unsure of why your particular example does not work. The mocked XMLHttpRequest object matches the API of the real XMLHttpRequest object. request.requestBody is the data attached to the body:

https://github.com/trek/pretender/blob/master/test/calling_test.js#L59-L74
