### ISSUE TITLE
[Proposal] - `all` Route Registerer

### ISSUE THREAD

**Issue by rtablada** [trek/pretender#67]
When working with routes (specifically passthrough) it would be helpful to have an `all` route registration to allow handling of any HTTP verb.

For instance if an API has gone from needing mocks to needing passthrough, the code now becomes:

```js
this.get('user', this.passthrough);
this.post('user', this.passthrough);
this.put('user', this.passthrough);
this.delete('user', this.passthrough);
```

**Comment by trek** [comment]
I need to see a PR to really understand. This seems like a major refactor.

**Comment by rtablada** [comment]
Yeah. I'm not completely sure what it would take and I've only glanced at the code so far. I'm planning a chat with @samselikoff some time next week to discuss some ideas on mocking APIs for design through tests, maybe join in?

**Comment by trek** [comment]
> maybe join in?

I'd be happy to. Can you send a http://doodle.com/ around with enough times that we can find a match?

**Comment by rtablada** [comment]
@trek @samselikoff, here is a link to figure out what time works for everyone

**Comment by trek** [comment]
Those times need to be a little finer grained for me... unless we actually need to chat for four hours?

**Comment by samselikoff** [comment]
I imagine it doesn't. @rtablada if this is just about the `.all` proposal as it related to the mirage issue, we could just PR it. It's essentially sugar for easily declaring a path to passthrough, for all HTTP verbs.

**Comment by rtablada** [comment]
@trek that was just my availability, haven't used doodle before.

@samselikoff I've been running into some other things, so I'm thinking that it will likely be a bit broader than just `.all` but if you had an idea on a PR that could free up some time.

**Comment by samselikoff** [comment]
Gotcha, would love to hear your thoughts.

Tomorrow at 11am-12 EST works for me.

**Comment by trek** [comment]
Closing from this going stale.
