### ISSUE TITLE
Progress events

### ISSUE THREAD

**Issue by cibernox** [trek/pretender#69]
According to the XHR2 specification (https://dvcs.w3.org/hg/xhr/raw-file/tip/Overview.html#make-progress-notifications): 

> while the download is progressing, queue a task to fire a progress event named progress about every 50ms or for every byte received, whichever is least frequent.

How do you feel about pretender triggering that event each 50ms by default? If nobody is listening, it's ok. Alternatively you can trigger only if there is an "onprogress" handler attached to the relevan object.

**Comment by cibernox** [comment]
Any feedback on this?

**Comment by trek** [comment]
Still haven't looked. You could speed up the process by providing more details about the pros/cons of this change.

**Comment by cibernox** [comment]
FakeXMLHttpRequest now can send `onprogress` events. According to the XHR spec, on progress events are triggered each 50ms during downloads and uploads

Usually you don't care about progress event, but sometimes I do. I was thinking in check if the request object has an `onprogress` event handler attached. If it does means that the user cares about them, and therefore I pretender should fire them regularly.

p.e. in a request with 200ms of delay the event, it would be fired each 50ms. Never before the `loadStart` and never after the `load` event.

**Comment by cibernox** [comment]
Sorry for the insistence, but I'm just waiting some green light to start implementing something.

**Comment by trek** [comment]
I'd still like to hear the pros/cons. I think you've accurately described the situation, but haven't touched on how it might affect people using the library's current behavior.

**Comment by cibernox** [comment]
I don't think that there is any cons. It's a new feature that should't affect in any form to current users.

The options are
a) Fire the events only if there is a listener for them.
b) Fire the events always.

Intuitively I think that option b) might be simpler to implement and triggering events is cheap enough to not be a concerned about wasting cycles. But in any case it's an implementation detail, the final result for the developer listening for progress events will be identical.

**Comment by trek** [comment]
> How do you feel about pretender triggering that event each 50ms by default?

Wouldn't we keep triggering events every 50ms, even after a test has finished running, whether you were using them or not? That seems like a high likelihood of ending up with test leaks?

**Comment by cibernox** [comment]
@trek see #73 for the implementation details. The change is fairly minimal and I don't see any posibility of leaking since the next progress event is scheduled only if the request is still ongoing.
