### ISSUE TITLE
allow to bypass if passthrough is specified

### ISSUE THREAD

**Issue by lessless** [trek/pretender#82]
Hello, there should be a way to interact with the 3rd party API, like S3 for example.

Right now even taking in account that passthrough is defined Pretender still throw an error: 

```  this.post('https://bucket.s3.amazonaws.com', this.passthrough);```
```javascript
Error: Pretender will not respond to requests for URLs. It is not possible to accurately simluate the browser's CSP. Remove the https://bucket.s3.amazonaws.com from https://bucket.s3.amazonaws.com/ and try again
```

**Comment by trek** [comment]
See #17, #20, #23, #39, #63
