### ISSUE TITLE
preprocessing requests

### ISSUE THREAD

**Issue by lessless** [trek/pretender#83]
Hello,

sometimes urls requests are performed by 3rd party libraries and they use an absolute url, like ` http://localhost:4200/api/v1/s3_mock`, when initial path was only `/api/v1/s3_mock`.

For that case it will be good to have some request pre-processing hook(s), which will allow altering request url,  something analogues to the `server.prepareBody` and `server.prepareHeaders` hooks.

**Comment by samselikoff** [comment]
#66 will fix this

**Comment by lessless** [comment]
@samselikoff I just gave a quick look on the routeRecognizer tests https://github.com/tildeio/route-recognizer/blob/master/tests/recognizer-tests.js and there are no cases for the absolute urls there. 
I'm not sure that it is designed to work with absolute urls at all.

**Comment by samselikoff** [comment]
But regardless, if Pretender handles absolute URLs we'll be able to as well, correct?

**Comment by trek** [comment]
Addressed by #66
